### ISSUE TITLE
Contour plot not produced for single-frame WRF output files

### ISSUE THREAD

**Issue by metroid2012** [anikfal/PostWRF#10]
Hi,
I
[wrfout_d01_2022-01-15_00:00:00.zip](https://github.com/anikfal/PostWRF/files/9301274/wrfout_d01_2022-01-15_00.00.00.zip)
'm trying to produce a contour plot of geopotential height at 500 Hpa from wrfout averaged file (find attached). However the ./postwrf.sh script won't produce the file saying the following error message:
fatal:Subscript out of range, error in subscript #0
fatal:An error occurred reading all_steps
fatal:["Execute.c":8637]:Execute: Error occurred at or near line 70 in file contourlvl.ncl
i've checked the file as well as the scripts but can't figure out what is going on. Could you help please?

**Comment by anikfal** [comment]
Hi,

WRF outputs are usually supposed to include 4D-variables with multiple time-slots. Your WRF output file has only one time. In other words, your file is not a real WRF file which includes variables with several time-slots.

I guess your WRF run was not complete. Or maybe this file is only an extraction from the main WRF file on a specific time-slot (if this is true, please use the main WRF file).

**Comment by metroid2012** [comment]
Hi, this is an output from WRF-Chem with volcanic ash modeling. The simulation was completed succesfully too.

**Comment by anikfal** [comment]
According to your namelist.wps:
```
start_date = '2022-01-10_00:00:00',
end_date   = '2022-01-25_00:00:00', 
```
You have a 15-day run. Supposing your `history_interval` in `namelist.wrf` is 60 minutes, and your `run-days` is the same, you must have about 360 (15*24) time-slots in your wrfout file. But you only have one time-slot. Therefore, I think your run was not complete, and there should have been some errors.

In your file, lets look at the variable `U`:
```
Variable: U
Type: float
Total Size: 819280 bytes
            204820 values
Number of Dimensions: 4
Dimensions and sizes:	[Time | 1] x [bottom_top | 44] x [south_north | 49] x [west_east_stag | 95]
Coordinates: 
Number Of Attributes: 6
  FieldType :	104
  MemoryOrder :	XYZ
  description :	x-wind component
  units :	m s-1
  stagger :	X
  coordinates :	XLONG_U XLAT_U XTIME
```
Look at `Dimensions and sizes`. The number of `Time` for the variable `U` and other variables such as `V`, `P`, and for your case `vash_1`, in a normal WRF or WRFChem output is always supposed to be more than 1. Logically, you run the model for a period of time, not just a moment!

**Comment by metroid2012** [comment]
Thank you for your valuable comments. The simulation is for 15 days. But i sent you the file to check why the script did not worked. If you want i can send 12 hours or a day of hourly data to check deeply the cause that prohibit the scripts to run.

**Comment by anikfal** [comment]
PostWRF will work on a normal WRF output file (your main output). But you can send a sample 12-hour output file. I will test it.

**Comment by anikfal** [comment]
Hi. Now I see what the problem is:

In your `namelist.input`, you have this setting: `frames_per_outfile = 1, 1,`. This means that each time-slot is stored in separate WRF output files. If you set `frames_per_outfile = 5, 5,`, the first five time-slots will be stored in the first WRF output file, the next five time-slots in the next WRF output, and so on. If you want all your time-slots to be stored in one single WRF output file, set `frames_per_outfile` to a large number (for example 1000).

But how can you work around this problem? You have two options:

- Run the model again with `frames_per_outfile = 1000, 1000,`

- Put all your unzipped WRF files in a separate directory and concatenate them to a single file with the command bellow:
`ncrcat -o wrfout_d01_2022-01-15_all wrfout_d01_2022-01-15_*`
notice the name of the output file (wrfout_d01_2022-01-15_all), you should give a name similar to a standard WRF output file (starting with wrfout_d)

**Comment by anikfal** [comment]
**For plotting geopotentials on 500hpa:**

- Modify the section `WRF CONTOUR PLOT` in `namelist.wrf` as bellow. You only need to modify `3rd_Variable_on_off`, `3rd_Variable_name` which is the keyword for geopotential , and `3rd_Variable_pressure_level` which is the atmospheric level. All other options can be turned off for this case:
```
CONTOUR_ON_OFF                  = 1

!!! Variable_1 by line contours !!!
1st_Variable_on_off             = 0
 1st_Variable_name              = T2
 1st_Variable_pressure_level    = 0
 1st_Variable_intervals         = 5
 1st_Variable_line_color        = red
 1st_Variable_line_thickness    = 0.5
 1st_Variable_label_size        = 0.5

!!! Variable_2 by (broken) line contours !!!
2nd_Variable_on_off             = 0
 2nd_Variable_name              = pvo
 2nd_Variable_pressure_level    = 700
 2nd_Variable_intervals         = 0
 2nd_Variable_line_color        = red
 2nd_Variable_line_thickness    = 0.5
 2nd_Variable_label_size        = 0.4
 2nd_Variable_brokenline_on_off = 1

!!! Variable_3 by filled (colored) contours !!!
3rd_Variable_on_off             = 1
 3rd_Variable_name              = geopt
 3rd_Variable_pressure_level    = 500,

Wind_Vectors_on_off             = 0
 Wind_Vectors_pressure_level    = 700
 Wind_Vectors_speed (m/s)       = 5
 Wind_Vectors_density           = 0.5
 Wind_Vectors_color             = black
 Wind_Vectors_thickness         = 0.5

Location_point_mark_on_off      = 0
 Location_labels_on_off         = 1
 Location_labels_size           = 0.2
 Location_labels_color          = black
Shapefile_on-off                = 0
 Shapefile_path                 = /home/anikfal/shapefiles/anazali_swamp.shp
```

- After saving `namelist.wrf`, link or copy your WRF output file (new concatenated file that we discussed about), and run postwrf.sh:

`./postwrf.sh`

While running the tool, you are supposed to answer some simple questions that are necessary for plotting configuration:

> ---------------------------------------------------------
>        CONTOUR PLOT                CONTOUR PLOT
> ---------------------------------------------------------
> 
> There are multiple wrf-files in the current directory:
> 
>    1) wrfout_d01_2022-01-15_all
>    2) wrfout_d01_2022-08-08_12:00:00
> 
> Enter the number of the favored file: 1
> 
> wrfout_d01_2022-01-15_all has been selected
> 
> Plotting  contour maps ...
> 
>  
> Specify Time_Step(s) Between The Images (Default=1): 1
> 
>  Specify The Method Of Drawing Contours (1 or 2) for geopt:
> 1) Automatic
> 2) Manual
> #? 2
> 
> Contour Lines Min Value (press Enter for the best value): 
>  Got no input. Best Min value will be set automatically.
> 
> Contour Lines Max Value (press Enter for the best value): 
>  Got no input. Best Max value will be set automatically.
> 
> 
> Select a color pattern from the list below (a number from 1 to 10) for geopt::
> 1) Rainbow-start_from_blue	 3) Rainbow-start_from_white	 5) Blue			 7) Green			 9) White..Black
> 2) Rainbow-start_from_red	 4) Blue..Red			 6) Red				 8) White..Yellow..Orange..Red	10) Black..White
> #? 1
> 
>  Format Of The Images: 1, 2, 3, or 4?
> 1) x11
> 2) pdf
> 3) png
> 4) animated_gif
> #? 3
> 
>  Name of the Output File? (Press Enter for the default name): australia
> Please wait. NCL is processing ...
> 
> Working on time: 2022-01-15_05:00:00
> Working on time: 2022-01-15_06:06:40
> Working on time: 2022-01-15_07:05:00
> Working on time: 2022-01-15_08:03:20
> Working on time: 2022-01-15_09:01:40
> Working on time: 2022-01-15_10:00:00
> Working on time: 2022-01-15_11:06:40
> Working on time: 2022-01-15_12:05:00

Geopotentials from WRF output on all time-slots will be plotted and saved as png image files. A sample is as bellow:

/home/anikfal/PostWRF/outputs_postwrf_wrfout_d01_2022-01-15_all/australia-wrfout_d01.000005.png

**Comment by metroid2012** [comment]
Hi,
i followed the steps you mentioned, but i got this error:

Error: one or more contour variables in namelist.wrf are not valid for postwrf_wrfout_d01_2022-01-15_all. Can you recheck please?

**Comment by anikfal** [comment]
Please copy the contour section of your `namelist.wrf` here. You must have put a wrong name for the contour variable.

**Comment by metroid2012** [comment]
Ok i solved the issue, i put by mistake ; geppotential on this line : 3rd_Variable_name              = geopt

if i want to plot the same variable for the average on these 12 hour files, how can i proceed?

**Comment by metroid2012** [comment]
Hi ,
now i want to plot era5 data's geopotential height. I noticed the the unit is converted to decameter, how can i restore it back to m²/s²?

**Comment by anikfal** [comment]
Hi,
You can always put a variable as polynomial. If you multiply the geopotential (z) by G (9.81) you will reach to its energy form (with unit m²/s²):
`3rd_ERA5_Var_name = z/9.81`

If you wan to see the names of the available variables in you ERA5 or WRF file, follow the command bellow:
`./postwrf.sh -f era5_file.nc`
> Variable names inside the file era5_file.nc:
> u10 ( time, latitude, longitude ) 
> v10 ( time, latitude, longitude ) 
> d2m ( time, latitude, longitude ) 
> t2m ( time, latitude, longitude ) 
> tp ( time, latitude, longitude ) 
>   Variables' description:
> long_name : 10 metre V wind component 
> long_name : 2 metre dewpoint temperature 
> long_name : 2 metre temperature 
> long_name : Total precipitation

You can also refer to the tool's documentations: https://postwrf.readthedocs.io/en/latest/index.html

**Comment by metroid2012** [comment]
thank you very much for the clarifications!

**Comment by metroid2012** [comment]
Thank you for the help, however, when i put the "3rd_ERA5_Var_name = z*9.81" i got the following error :

**./contourlvl_sed3.sh: 23: Syntax error: "(" unexpected (expecting "fi")**
(0)	Please wait. NCL is processing ...
(0)	
**fatal:Variable (tc_plane33) is undefined
fatal:["Execute.c":8637]:Execute: Error occurred at or near line 281 in file contourlvl_era_equation.ncl**

**Comment by anikfal** [comment]
Please send me your ERA5 file. So I can check the issue.
