### ISSUE TITLE
Converting to Geotiff

### ISSUE THREAD

**Issue by meteomanic** [anikfal/PostWRF#13]
[namelist_wrf.txt](https://github.com/anikfal/PostWRF/files/10083087/namelist_wrf.txt)

Hi,

I am encountering the following error when generating the Geotiff file from the wrfout file for a single time (By making the history interval to 1 in namelist.input while running WRF). However, I am able to generate geotiff for wrfout with all time steps together.

Converting to Geotiff. Please wait ...

fatal:Subscript out of range, error in subscript #0
fatal:An error occurred reading all_steps
fatal:["Execute.c":8637]:Execute: Error occurred at or near line 21 in file /home/raghu/PostWRF/modules/geotiff.ncl

cat: /home/raghu/PostWRF/modules/geo_eq_ok.txt: No such file or directory

Could you please help me in fixing the issue.

**Comment by anikfal** [comment]
Hi. Thank you for reporting this problem.
It seems there is a problem in the source code. I need a couple of days to work on that and fix it.

**Comment by anikfal** [comment]
Please pull the updates, or clone the updated software and try your task again, and report the results. I want to be sure that your problem is solved.

**Comment by meteomanic** [comment]
Hi, Thank you for the update and is working fine with Geotiff. However, facing a very similar issue with plotting other maps (Ex. contour maps and skew-T etc).

**Comment by anikfal** [comment]
Yes. This was actually a bug in the software, when the WRF output has only one single time. The remaining tasks (contour maps, cross-section maps, ...) will be updated in a couple of days.

Thank you for the good first issue!

In case of any other problems, you can continue commenting on this issue, or making new ones.

**Comment by meteomanic** [comment]
Thanks for the update. Will get back to you if I have  any issues.

Thanks

**Comment by meteomanic** [comment]
Hi,

Thank you very much for your help in fixing the previous issue. However, I am looking to automatically process the hourly wrfout files from the same run (multiple files). I have tried with some scripts by looping but couldn't able to do a successful process.

Thanks and regards,
Raghu

**Comment by meteomanic** [comment]
Hi,

Thanks for the response. When I am executing the command as you mention, encounter the below error message.

**_raghu@elogin04:~/PostWRF-master> ./postwrf.sh wrfout_d01_2023-02-21_00\:00\:00,wrfout_d01_2023-02-21_01:00:00_**

> =================  PostWRF (Version 1.1)  =====================
>               Run './postwrf.sh -h' to get help
>    In case of problems, please contact <ah.nikfal@gmail.com>
> ===============================================================
> 
> ---------------------------------------------------------
>       CONVERT TO GEOTIFF          CONVERT TO GEOTIFF
> ---------------------------------------------------------
> 
> 
> Specify Time_Step(s) Between The Images (Default=1):
> Time_Step Has Been Set To 1
> ls: cannot access '/home/raghu/PostWRF-master/postwrf_wrfout*': No such file or directory
> basename: missing operand
> Try 'basename --help' for more information.
> 
> ---------------------------------------------------------------
> Converting to Geotiff. Please wait ...
> warning:_NclOpenFile: cannot open file </home/raghu/PostWRF-master/outputs_/postwrf_wrfout*>; No such file or directory
> 
> fatal:Subscript out of range, error in subscript #0
> fatal:An error occurred reading fileatts
> fatal:["Execute.c":8637]:Execute: Error occurred at or near line 15 in file read_wrfouts.ncl
> 
> cat: /home/raghu/PostWRF-master/modules/geo_eq_ok.txt: No such file or directory

Thanks and regards,
Raghu

**Comment by anikfal** [comment]
What are the names of your WRF files?

**Comment by meteomanic** [comment]
My wrfout file naming is as follows:

wrfout_d01_2022_12_03-00:00:00
wrfout_d01_2022_12_03-01:00:00
wrfout_d01_2022_12_03-02:00:00
wrfout_d01_2022_12_03-03:00:00
.
.
.
.
wrfout_d01_2022_12_06-01:00:00
wrfout_d01_2022_12_06-02:00:00
wrfout_d01_2022_12_03-03:00:00

**Comment by anikfal** [comment]
Please send me at least 2 consecutive files of that list.
