### ISSUE TITLE
hdf5  mismatch

### ISSUE THREAD

**Issue by fipoucat** [anikfal/PostWRF#14]
i am getting the following error and wonder how to fix it?
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.12.2, library is 1.10.7
	    SUMMARY OF THE HDF5 CONFIGURATION

**Comment by anikfal** [comment]
Hi. Please provide detailed information. Which section of namelist.wrf are you running? On what kind of data? WRF or ERA5? ...

**Comment by fipoucat** [comment]
I think I have to check the wrf output, maybe something wrong with hdf5 during compilation. I have the same behavior when I use cdo too.

**Comment by anikfal** [comment]
Can you open and visualize your WRF output with ncview? As far as I know, hdf5 is not a necessary library for WRF.

**Comment by fipoucat** [comment]
Tes, I can plot the output with ncview because it is a netcdf file so I am
confused why it complains with hdf5

**Comment by fipoucat** [comment]
the  kind of error I notice:
./modules/extract.sh: line 137: 16021 Aborted                 (core dumped) ncl -nQ profile.ncl

my namelist:
======================= DATA EXTRACTION (ON SURFACE) ========================
=============================================================================
Extract_On-Off                  = 1

WRF_variable_name               = T2, rh
Location_names                  = Dakar, Podor
Location_latitudes              = -17.41, -14.57
Location_longitudes             = 14.49, 16.40

+Vertical_profile_plot_on_off   = 1
+Vprofile_X_axis_decimals       = 3
---------------------------------------

**Comment by fipoucat** [comment]
the job finished but output directory empty?
Bye...
./modules/extract.sh: line 137: 21976 Aborted                 (core dumped)
ncl -nQ extract.ncl

PostWRF: Extracting variables finished.

**Comment by anikfal** [comment]
Please run the command below on your `wrfout` and send `output.nc` to me (you need to install `nco`):
`ncrcat -d Time,0,1 wrfout output.nc`

It seems something is wrong with your `wrfout`

**Comment by fipoucat** [comment]
there is a size problem 28mb while only 25 possible

**Comment by fipoucat** [comment]
[](url)
[output.txt](https://github.com/anikfal/PostWRF/files/10346414/output.txt)

**Comment by anikfal** [comment]
Please send my by email:
ah.nikfal{at}gmail.com

**Comment by fipoucat** [comment]
Did you get the file? if so is there any problem or the file is just fine.

**Comment by anikfal** [comment]
No. I have not yet received any file by email.

**Comment by anikfal** [comment]
I tested the file (output.nc) you sent to me. Every things were okay.
So there is a problem with your system (NCL installation perhaps).

A sample output for extracting relative humidity over some points:
```
---------------------------------------------------------------------------
 WRF output variable: rh (Relative Humidity) - unit_scale: %
----------------------------------------------------------------------------
               Time Algiers_(37.21-3.03) Marrakesh_(31.67--7.98) Dakar_(14.88--17.44)
2002-01-10_00:00:00               69.04               35.73               84.65
2002-01-10_03:00:00               71.97               36.67               87.94
```

A sample contour plot:

![contour-level-wrfout_d01 000002](https://user-images.githubusercontent.com/11738727/216570955-c5854835-bceb-4793-9369-e27c2e23ff3c.png)

**Comment by fipoucat** [comment]
Ok, my ncl is 6.6.2 so I'll check the installation again. Your fig is what I expect. I'll update you when successful.

**Comment by fipoucat** [comment]
working after reinstalling ncl,

Many thanks
