### ISSUE TITLE
 PostWRF execution problem

### ISSUE THREAD

**Issue by lbdieng** [anikfal/PostWRF#15]
Thank you very much for sharing the PostWRF software
I would like to use it to get the simulated WRF  IR brightness  temperature.
I have followed all the steps in your tutorial. However, when I ran the script ( /PostWRF-master$ ./postwrf.sh ). I see  the following error messages

 
Processing *_values_*.dat ...
fatal:asciiread: Unable to open input file (*_values_*.dat)
fatal:["Execute.c":8637]:Execute: Error occurred at or near line 7 in file rttov_output.ncl
fatal:Undefined identifier: (AllLines) is undefined, can't continue
fatal:["Execute.c":8637]:Execute: Error occurred at or near line 11 in file rttov_output.ncl
fatal:Variable (allbands) is undefined
fatal:["Execute.c":8637]:Execute: Error occurred at or near line 12 in file rttov_output.ncl
fatal:Variable (rttovvar) is undefined
fatal:["Execute.c":8637]:Execute: Error occurred at or near line 13 in file rttov_output.ncl
fatal:Variable (rttovvar) is undefined
fatal:["Execute.c":8637]:Execute: Error occurred at or near line 14 in file rttov_output.ncl
fatal:Variable (allbands) is undefined
fatal:["Execute.c":8637]:Execute: Error occurred at or near line 22 in file rttov_output.ncl

Do you have any ideas on this problem?

**Comment by anikfal** [comment]
Hi,

Please send your `namelist.wrf`.

Also please run the command below on your `wrfout` and send `output.nc` to me (you need to install nco):
`ncrcat -d Time,0,1 wrfout output.nc`

After receiving your files, I will check it out.

**Comment by NishantBehera** [comment]
![20240114_120150](https://github.com/anikfal/PostWRF/assets/120490361/b34ba565-89e5-4a2a-a2cc-8b6885fee764)

Getting this error

**Comment by anikfal** [comment]
Please attach your `namelist.wrf`.
Such an image does not provide much information.

**Comment by NishantBehera** [comment]
> Please attach your `namelist.wrf`. Such an image does not provide much information.

Sir the issue is solved

**Comment by MrHoneyB** [comment]
If we want to plot the contour plot for pressure(hpa) and geopotential what should be the contour interval. for my case i am getting warning.

warning:ContourPlotSetValues: Invalid level spacing value set: defaulting
warning:ContourPlotSetValues: Invalid level values set: using AUTOMATICLEVELS mode

and the plot is something like this. How to resolve this

![contour-level-wrfout_d01 000002](https://github.com/anikfal/PostWRF/assets/120490361/563e0163-7b28-4b14-985d-bc0c2c581c8b)

**Comment by anikfal** [comment]
@MrHoneyB For new/different subjects, please make new issues.

Your domain seems to be covered with high mountains, with elevations up to 2000 m or higher. So you must set an appropriate atmospheric pressure level in `namelist.wrf`. Reasonably, values more than 800 (representing altitudes of 2000 m or lower) or even 700 (~ altitudes of 3000 m) cannot be plotted for such a domain.

By values of ~ 700 hpa or less (600, 500, etc.) for the pressure level, there should be no problem for this domain.
