### ISSUE TITLE
Not showing shaded map (Ubuntu issue)

### ISSUE THREAD

**Issue by tinpk85** [anikfal/PostWRF#16]
Hi bro, I have problem with "Variable_3 by shaded contours". My result not showing shaded map (also no error message)
(I used your namelist.wrf). How can fix it ?
![Capture](https://github.com/anikfal/PostWRF/assets/56418686/75faca19-f3ce-4455-9877-407a75dde36b)
[namelist.wrf.txt](https://github.com/anikfal/PostWRF/files/11881017/namelist.wrf.txt).

**Comment by anikfal** [comment]
Hi.
Is this image the only result? What about other plots (next time slots)? All of them are empty?

The namelist looks fine to me. Maybe there are some issues with your WRF file. If the size of your WRF file is not much large, can you please send it to me to take a look at it? My email is ah.nikfal (gmail.com).

If the size of your WRF file is very large, you can run the command below and send `output.nc` to me instead. For running this command, you need to install NCO on your machine.
`ncrcat -d Time,0,1 wrfout output.nc`

**Comment by tinpk85** [comment]
Hi.
 My result only show contour map.
This is my wrfout. 
[output.nc.txt](https://github.com/anikfal/PostWRF/files/11881267/output.nc.txt)

**Comment by anikfal** [comment]
Thanks for sending the file. Your WRF file is okay.

In your `namelist.wrf`, please put `Location_point_mark_on_off` and `Shapefile_on-off` to 0, and plot again. It will be plotted without problem.
If you want to overlay points and shapefile on your plots, please try to give correct values and path to the aforementioned parameters, as well as `Location_names`, `Location_latitudes`, and `Location_longitudes`.

**Sample output:**
![contour-level-wrfout_d01 000002](https://github.com/anikfal/PostWRF/assets/11738727/64e6d71f-270c-4dfb-9877-12bafb20e1c1)

**Comment by anikfal** [comment]
Your shapefile should also have a lat/lon projection to be overlaid on the plot. If the projection is something else (e.g. UTM), you can convert it to lat/lon and give its path to namelist.wrf.

**Comment by tinpk85** [comment]
Hi.
I edited namelist.wrf, but it still not showing (contour map is good). Maybe library  is problem.
[namelist.wrf.txt](https://github.com/anikfal/PostWRF/files/11882019/namelist.wrf.txt)

![usagi-wrfout_d02 000030](https://github.com/anikfal/PostWRF/assets/56418686/dd7b2c0d-72b0-4b6c-907d-6ab1f441fdfe)

**Comment by anikfal** [comment]
I ran it again with your new namelist and the plot was okay.

What is your system information? Your Linux distro? NCL version?
Does it show any error while you're running PostWRF?

**Comment by tinpk85** [comment]
Hi.
My system is Ubuntu 23.04 (Desktop). NCL 6.6.2
No error while running .
[Postwrf.log](https://github.com/anikfal/PostWRF/files/11882410/Postwrf.log)

**Comment by anikfal** [comment]
Try again, but in the last step (`Format Of The Images: 1, 2, 3, or 4?`), choose 2 (pdf) or 3 (png).
Maybe your system cannot handle `x11`.

**Comment by tinpk85** [comment]
> Try again, but in the last step (`Format Of The Images: 1, 2, 3, or 4?`), choose 2 (pdf) or 3 (png). Maybe your system cannot handle `x11`.
> 
> In case of pdf or png, your plots will be saved in directories started by `outputs_postwrf`.

I have tried with 2 (pdf) and 3 (png) but the result is still the same.

**Comment by anikfal** [comment]
Put the NCL lines below in a file (1.ncl) and run it.
Before running, replace the file name in the line `f = addfile ("wrfout_d01_2020-01-15_____", "r")` with your own WRF file name.

```
begin
;---Open file; substitute your own WRF output file here
  f = addfile ("wrfout_d01_2020-01-15_____", "r")
;--Read variables
  times = wrf_user_getvar(f,"times",-1)  ; get all time values on file
  p     = wrf_user_getvar(f,"p",-1)  ; calculate pressure across all time, levels
  nt = 0 ; timestep to plot
  nl = 0 ; level to plot
;---Create simple contour plots
  wks = gsn_open_wks("png" ,"wrf_plot")
  res                       = True            ; plot mods desired
  res@gsnMaximize           = True            ; maximize plot size
  res@tiMainString          = times(nt)       ; main title
  res@cnFillOn              = True                 ; turn on color
  res@cnFillPalette         = "BlAqGrYeOrReVi200"  ; change color map
  res@cnLinesOn             = False           ; turn off contour lines
  plot                      = gsn_csm_contour(wks,p(nt,nl,:,:),res)
end
```
After running `ncl 1.ncl`, you should have a png (pdf) file starting by `wrf_plot`. Does it show any colors?
I was thinking maybe some problem is with your NCL.

**Comment by tinpk85** [comment]
Hi,
 I run 1.ncl , the result is same. i 'll try reinstall NCL.
Thank for helping.
![Uploading wrf_plot.png…]()

**Comment by tinpk85** [comment]
Hi.
I reinstall NCL 6.4 and it works now, seem problem with NCL 6.6.2.

Thank for support.

**Comment by anikfal** [comment]
Hi. I tested it for this new issue and it was okay in my system (Fedora). However, it seems to have problems in Ubuntu.
I think your only option is to run PostWRF in CentOS, Fedora, Redhad, or similar OS. But not Ubuntu.

I will try to handle the issue to make it possible to work in Ubuntu without problem.

**Comment by anikfal** [comment]
I found the problem. That was a bug in the code. I will try to solve it today.
Please clone PostWRF tomorrow. It will work for Ubuntu.
