### ISSUE TITLE
Problem with Extracting variables

### ISSUE THREAD

**Issue by tinpk85** [anikfal/PostWRF#17]
Hi bro.
- After reinstallation Ubuntu 23.04. I got error with Extracting variables (WRFoutput and ERA5 data)
For WRFoutput :
"warning:stringtofloat: a bad value was passed; input strings must contain numeric digits, replacing with missing value
warning:stringtofloat: a bad value was passed; input strings must contain numeric digits, replacing with missing value
Range of Domain Latitudes (south-north): 5.32 to 21.19
Range of Domain Longitudes (west-east) : 100.7 to 118.45
fatal:Dimension sizes on right hand side of assignment do not match dimension sizes of left hand side
fatal:["Execute.c":8640]:Execute: Error occurred at or near line 399 in file extract.ncl  "

For ERA5 data : 
( PostWRF: Extracting variables ...
warning:stringtofloat: a bad value was passed; input strings must contain numeric digits, replacing with missing value
warning:stringtofloat: a bad value was passed; input strings must contain numeric digits, replacing with missing value
Range of Domain Latitudes (south-north): 5 to 20
Range of D
[namelist.wrf.txt](https://github.com/anikfal/PostWRF/files/12035190/namelist.wrf.txt)
omain Longitudes (west-east) : 100 to 120
fatal:Dimension sizes on right hand side of assignment do not match dimension sizes of left hand side
fatal:["Execute.c":8640]:Execute: Error occurred at or near line 229 in file extract_era.ncl
PostWRF: Extracting variables finished.)
. I tried NCL 6.6.2 and 6.4.0 but the result shows same error.

Pls help me. Thank you

**Comment by anikfal** [comment]
Hi,
In your `namelist.wrf`, please remove the spaces after the lat/lon values:
```
Location_names                   = Hochiminh
Location_latitudes               = 10.667,
Location_longitudes              = 106.667,
```
Those spaces after `10.667, ` and `106.667, ` are considered as values (which are not) and cause error.
I may modify the tool to avoid such issues.
