### ISSUE TITLE
Need Help in Domain plot  with shapefiles&Time Series Plot for Model and Observation in single graph

### ISSUE THREAD

**Issue by paparao123** [anikfal/PostWRF#21]
Hi all,
I'm having trouble generating  Domain plot with shape files and another query is  time series plot that combines both model and observation data on a single graph. I've attempted to use both model extracted data it named as "values-T2-Bilinear" and observational data named as observations-T2-Bilinear,but haven't had plot in single graph for both model and observation for single location . If anyone has experience with this please suggest me in this regard, I would be very grateful.

Thank you in advance for your assistance!

**Comment by anikfal** [comment]
Hi,

There are 3 parts in `WRF STATISTICAL DIAGRAMS`:
1) Time series
2) Scatter plot
3) Taylor diagram

For the time series plots, all values for model and observations will be plotted as time series.

For Scatter plot and Taylor diagram, values of model/observations will be plotted as a single plot for each variable. So I think you were using Time-series. However you may need to disable it (`Timeseries_ON_OFF = 0`), and enable the scatter plot (Scatterplot_ON_OFF = 1).

For more information, please read: https://postwrf.readthedocs.io/en/latest/statistical.html
