### ISSUE TITLE
How to add the specific location point names in postwrf 

### ISSUE THREAD

**Issue by paparao123** [anikfal/PostWRF#23]
Hi all , am seeking the guidance how to add specific location point names into contour plots in Postwrf. Specifically, I am interested in adding location names based on latitude and longitude coordinates.

**Comment by anikfal** [comment]
Information of your lat/long and location names are read from the `WRF/ERA5 DATA EXTRACTION (ON SURFACE)`.
 Then if you have enabled `Location_point_mark_on_off`, they will be plotted on your map.\
Take a look at https://postwrf.readthedocs.io/en/latest/contour.html#example-1

**Comment by paparao123** [comment]
> Information of your lat/long and location names are read from the `WRF/ERA5 DATA EXTRACTION (ON SURFACE)`. Then if you have enabled `Location_point_mark_on_off`, they will be plotted on your map. Take a look at https://postwrf.readthedocs.io/en/latest/contour.html#example-1

Thank you for quick reply , i have got your point

**Comment by paparao123** [comment]
Thankyou so much for the quick reply I resolve the issue it it amazing tool
