### ISSUE TITLE
  plotting the average over a span of 20 days (480hrs):Unable to allocate memory for output array

### ISSUE THREAD

**Issue by paparao123** [anikfal/PostWRF#24]
Hello everyone, I'm encountering the following error when trying to plotting the average over a span of 20 days (480 hours) from my WRF daily output files.please help me in this regard.

"fatal:wrf_tk: Unable to allocate memory for output array
fatal:["Execute.c":8637]:Execute: Error occurred at or near line 1300 in file $NCARG_ROOT/lib/ncarg/nclscripts/wrf/WRFUserARW.ncl

fatal:["Execute.c":8637]:Execute: Error occurred at or near line 335 in file /home/paparao/CAPS/Postwrf/modules/contourlvl.ncl"

== GENERAL SETTINGS ==============================
=============================================================================
spin-up_time (hours)             = 6
averaging_on_off                 = 1
 average_time (hours)            = 480
panel_plot__on_off               = 1
 panel_plot__rows_number         = 2
 panel_plot__columns_number      = 3
smooth_maps_on_off               = 1
map_borderline_color             = black
map_borderline_thickness         = 0.2
map_filled_ocean_on_off          = 1
map_gridlines_on_off             = 1
plot_titles_on_off               = 1

**Comment by paparao123** [comment]
Thank you for your suggestion. I'm actually looking to create plots for
monthly or seasonal averages. Currently, I have daily WRF output files.
Once again thankyou for your help
Regards
Paparao

**Comment by anikfal** [comment]
You mean hourly WRF outputs?
The purpose of WRF as a regional model was not for monthly or seasonal averages. For those aims, climate data or atmospheric global data, such as ERA5 or FNL, are good options to be used.
