### ISSUE TITLE
to extract wind speed, direction

### ISSUE THREAD

**Issue by AbdBaten** [anikfal/PostWRF#26]
Dear Mr. Amir Hossain,

I have successfully run the wrf with fnl data. I was using postWRF to plot windrose and to extract the WS and WD from the wrf output file. While, by following your training video, I was able to plot the windrose, I was getting problem in data extraction on a particular lat/lon point. Can you please help me in this regard?

Thanks with best regards,
Masud Rana

**Comment by anikfal** [comment]
Hi. Perhaps the lat/lon values were out of your WRF domain. If not, please provide `namelist.wrf` and the error you face while running it.

**Comment by AbdBaten** [comment]
> Hi. Perhaps the lat/lon values were out of your WRF domain. If not, please provide `namelist.wrf` and the error you face while running it.

Thank you. Let me try again.
