### ISSUE TITLE
remove world boundary 

### ISSUE THREAD

**Issue by piyushgupta174** [anikfal/PostWRF#27]
I just want to remove auto plot of world boundary in ncl and just wan to plot my edited shape file for specific area. 
I have already tried by setting  - 
map_borderline_color             = black
map_borderline_thickness         = 0
but it is reducing thickness for world map and also my shape file map boundary thickness.
Can you please help, where to find and disable the world map shape file in ncl. 
or how can I overwrite that file with my edited shape file.
Thankyou

**Comment by anikfal** [comment]
I added a new capability to PostWRF's namelist.wrf, so now you can remove world map boundaries.

Please `git pull`, or clone PostWRF again into your system. In the new PostWRF, you can find a new variable: `borderline_on_off`. If you set it to 0, border lines of the countries will be removed from your plots.
