### ISSUE TITLE
How to extract the selected  varaibles in particular  lcoation and save csv format

### ISSUE THREAD

**Issue by paparao123** [anikfal/PostWRF#28]
Dear all, 
I am delighted to utilize the PostWRF, and I am seeking assistance in extracting specific variables from the WRF output file (WRFOUT). The variables of interest are psfc (surface pressure), temp (temperature), wspd (wind speed), and wdir (wind direction) at a particular location. Ideally, I would like to save this information in a CSV file named wrf_hrly_(name).csv .The format of the file should be as follows. Please help me in this regard .
thank you 

Date                                    psfc                temp               wspd                  wdir       
2019-01-01_00:00:00         98644.47        25.37              1.72                  168.86
2019-01-01_01:00:00         96644.47        26.54                2.0                   195.54

**Comment by anikfal** [comment]
Hi @paparao123 

Have you taken a look at the documentation or the YouTube training videos?
https://postwrf.readthedocs.io/en/latest/extraction.html#time-series-of-the-wrf-variables

PostWRF is currently not capable of saving the extracted values as CSV. This capability will be added in near future.
However, you can simply use a spread-sheet software (Excel, LibreOffice, ...) to convert the extracted values to CSV.

**Comment by paparao123** [comment]
Hi Anikfal thank you for reply , currently i am extracted  for all locations but it is individual files   I am  looking extracting specific variables are  like 4 to 5 variables at a particular location. Date psfc temp wspd wdir all in extracted in single file 
2019-01-01_00:00:00 98644.47 25.37 1.72 168.86
2019-01-01_01:00:00 96644.47 26.54 2.0 195.54

**Comment by NishantBehera** [comment]
Dear all, 
when we are extracting PM10 and PM2.5 values using postwrf at what height it is giving us the value?

**Comment by anikfal** [comment]
Hi @NishantBehera 
Extracting in PostWRF is only for the surface layer. So it will be possible to compare it with station data. For the values on atmospheric pressures, you can use cross-section plots or vertical profile plot.

**Comment by NishantBehera** [comment]
Hi, can we extract the PBL height from the output file with the help of PostWRF?

**Comment by anikfal** [comment]
@NishantBehera 
PBL height is directly simulated by WRF and is available in the WRF otput file.
Just put `PBLH` as the variable name in the extraction section of `namelist.wrf` and run `postwrf.sh`.

**Comment by NishantBehera** [comment]
Is there any way how we can find out the value of bulk richardson number with the help of postwrf

**Comment by anikfal** [comment]
As far as I know, by modifying `namelist.input` with regard to the PBL scheme, some variables related to the turbulent kinetic energy (not necessarily the Richardson number) can be simulated and be available in the WRF output.

**Comment by NishantBehera** [comment]
In the contour map plot section is there any way to obtain only the wind vector keeping all other off

**Comment by anikfal** [comment]
@MrHoneyB Yes. Just do as you said. Enable wind vector and disable other options.
