### ISSUE TITLE
Atmospheric pressure level in contour plot

### ISSUE THREAD

**Issue by MrHoneyB** [anikfal/PostWRF#31]
Even decreasing the pressure level to 400 hpa from 750 not able to resolve the problem. Getting the warning message.

warning:ContourPlotInitialize: scalar field is constant; no contour lines will appear; use cnConstFEnableFill to enable fill
warning:ContourPlotSetValues: Invalid level spacing value set: defaulting
warning:ContourPlotSetValues: Invalid level values set: using AUTOMATICLEVELS mode
warning:ContourPlotSetValues: Data values out of range of levels set by MANUALLEVELS mode

![contour-level-wrfout_d01 000002](https://github.com/anikfal/PostWRF/assets/120490361/8d8f3372-a375-4b0e-a594-bbadddddb336)

How to reslove this.

**Comment by MrHoneyB** [comment]
> Send me your `namelist.wrf` please. You can attach it here.

[namelist.txt](https://github.com/anikfal/PostWRF/files/13964336/namelist.txt)

**Comment by MrHoneyB** [comment]
Basically, I want to find is there any low or high pressure level exist over my domain. So how can i do that??

**Comment by anikfal** [comment]
Can you run `postwrf.sh` with the namelist you sent? What is is your OS?

**Comment by MrHoneyB** [comment]
> Can you run `postwrf.sh` with the namelist you sent? What is is your OS? Send me the exact `namelist.wrf` you are using with PostWRF. Do not change it to other file.

https://drive.google.com/drive/folders/1N41QxWa8AQgqssRsoaDe-Gy-MlOonsWR?usp=drive_link

uploaded the exact file in the above g-drive.

**Comment by anikfal** [comment]
At first that was confusing for me. But now it is clear.

Actually you should use `1st_Variable_name = geopotential`.
On an atmospheric pressure level (say 400 hpa) there will be no contour lines for pressure, since there is no variation in pressure, and all pressure values are equal to 400 hpa in that level.
