### ISSUE TITLE
Cloud cover 

### ISSUE THREAD

**Issue by MrHoneyB** [anikfal/PostWRF#33]
Is there any way to find Cloud cover or sunshine duration data using postwrf?

**Comment by anikfal** [comment]
There is a cloud fraction variable (`CLDFRA`) inside the WRF output which can be plotted by PostWRF over the atmospheric pressure levels.

At the moment, PostWRF does not directly calculate sunshine hours. However, you can use some NCL functions to estimate sunshine:
https://www.ncl.ucar.edu/Document/Functions/Crop/radsol2_fao56.shtml
https://www.ncl.ucar.edu/Document/Functions/Crop/radsol_fao56.shtml
https://www.ncl.ucar.edu/Document/Functions/Crop/radext_fao56.shtml
https://www.ncl.ucar.edu/Document/Functions/Crop/daylight_fao56.shtml

Moreover, there is a shortwave radiation variable (`SWDOWN`) inside the WRF output, which can be plotted by PostWRF.
