### ISSUE TITLE
Geotiff conversion - output resolution does not match the model run

### ISSUE THREAD

**Issue by Tomo1583** [anikfal/PostWRF#34]
Greetings! 
I have started using the PostWRF recently and I must admit that it is a really useful tool for quick model data processing! 
Ive been using it for couple of days, however I ran into a problem when exporting the data into geotiff format. The resolution of all exported tiffs suddenly does not match the resolution of the model output for all domains. For example, parent domain with model resolution of 5 km have 8 km raster resolution as geotiff and nested domain with 1,5 km have also the resolution of about 8 km (in ncview and other SW the resolution is correct). The generated tiffs have correct space coordinates and data, despite the resolution, apparently match the timeframe. 
The same error also occurs with other WRF model runs, which previously worked correctly and even after reinstalling the PostWRF from scratch. Only "WRF CONVERT TO GEOTIFF" part of namelist.wrf was edited according the documentation.
Am I missing something obvious or is it some kind of error?

Best regards.

![geotiff](https://github.com/anikfal/PostWRF/assets/157398278/8e564dd8-3cb4-4a8b-9a19-fedd0fa725a1)
![ncview](https://github.com/anikfal/PostWRF/assets/157398278/e3b2146a-d9b4-41f6-ae74-a35c68d9a229)

**Comment by anikfal** [comment]
Hi @Tomo1583 
No matter what is the resolution of the WRF output, GeoTIFF images from PostWRF will be generated based on 0.1 degree (about 9km on mid-latitudes). However, this issue will be updated in the next version of PostWRF to conform to the original resolution of the WRF output.

**Comment by anikfal** [comment]
A new capability has been added to PostWRF to handle this issue.

You can `git pull` or clone PostWRF again. In the Geotiff section, a new parameter (`tiff_resolution (km)`) has been added. You can set it to your desired value (10 km, 20 km, etc.).
If you set `tiff_resolution (km) = 0`, the output tiff files will be made in the same resolution of the original WRF output.
