### ISSUE TITLE
Relative Vorticity

### ISSUE THREAD

**Issue by MrHoneyB** [anikfal/PostWRF#35]
How can we extract the value of relative vorticity?

**Comment by anikfal** [comment]
Regarding `./postwrf.sh -d`, you can see the absolute vorticity (`avo`) is among the list of diagnostic variables. So you can extract it by setting the variable name to `avo`.

With regard to the equation below, you can calculate relative vorticity. Just subtract the Coriolis parameter from the absolute vorticity:
Absolute vorticity = relative vorticity + Coriolis parameter
