### ISSUE TITLE
Transboundary Air Pollution

### ISSUE THREAD

**Issue by MrHoneyB** [anikfal/postwrf#38]
I successfully run WRF-Chem model with two domain. If I want to calculate what percentage of pollution from outer domain is contributing to inner domain. How can I do so ?

**Comment by anikfal** [comment]
I am not totally sure at the moment. But maybe you can set the emissions values of the nested (smallest) domain to zero, and run the model again. In this case all pollution inside the nested domain originate from outside of it.

**Comment by MrHoneyB** [comment]
How can we set the emission values of nested domain as zero? Any Idea

**Comment by MrHoneyB** [comment]
Can we find the total emission originating from a domain ?

**Comment by anikfal** [comment]
I have not tried it before. But the settings you mentioned seems no to be effective. Because the area should be modified in all domains. In other words, emissions must be zero in the nested domain and the associated area in the parent domain as well.

Another method of setting the emissions to zero is modifying the files and manually set the emissions to zero (and running normally). You can do that by NCL. I am also preparing a tool for modifying WRF files for a desired variable. I will share it in near future.

**Comment by MrHoneyB** [comment]
It means that first we have to run the anthro_emiss to generate anthropogenic emssion file . Then we have to run real.exe and after that we have to set the value of emission outside the nested domain to zero by modifying the wrfinput files. Then we have to run the wrf.exe.

**Comment by MrHoneyB** [comment]
Edgar emissions are Yearly data , can you please explain how the WRF model is able to convert it to a hourly data?

**Comment by anikfal** [comment]
There is no special conversion from yearly to hourly. It's not possible. You can simply use the same yearly emissions data for your simulation in any day inside that year.

**Comment by MrHoneyB** [comment]
No sir my doubt is that the Edgar data set are monthly emissions file, then how the wrf-chem model is able to generate hourly emissions.  (I want to know how Anthro preprocessor able to do that)

**Comment by anikfal** [comment]
`anthro_emiss` does not generate hourly emissions. But it extracts emissions for a specific hour of a specific day. And you use that single file for several hours and days. You assume the emissions are almost static, without significant variations.
But if you have hourly emissions data (e.g. the data for North America), you can use anthro to make emissions for several hours. So making hourly emissions with monthly data is not much possible.

**Comment by MrHoneyB** [comment]
The EDGAR-HTAP dataset is a monthly dataset (1st day of each month) having lat-lon projection for 2010 at a resolution of 0.1 deg * 0.1 deg. However, the WRF model domain has a different spatial resolution and projection. Then, how is the emission mapping being done?
And if we are interested in doing the simulation for February 2024, does it consider the emission of February 2010 and map it to our domain? These emission files (wrfchemi_00z_d<nn> and wrfchemi_12z_d<nn>) act as an initial condition and model time integration to generate future emissions.
Can you kindly explain?

**Comment by anikfal** [comment]
The WRF/Chem utilities for emissions data (prep_chem, anthro_emiss, etc.) actually interpolate emissions data over the domain's grid points.
For Feb. 2024, you need to use recent emissions data. There are also some data repositories for real time emissions, which I mentioned in the YouTube videos.

**Comment by MrHoneyB** [comment]
When we assign the value of data_offset_yr in the anthro preprocessor, it just makes available the data for that year, the year for which we are doing the simulation by changing the year of the dataset( adding the data_offset_yr to the original emission file), but the emission remain unchanged?

Or does it perform some temporal scaling?

**Comment by anikfal** [comment]
I think the emissions remain unchanged. But try to investigate it more.
I am currently working on a new utility called WRFtailor (https://github.com/anikfal/wrftailor) which you can use for modifying WRF input data over an area of interest. It's under development, but can be used with some limitations.
