### ISSUE TITLE
Mozbc

### ISSUE THREAD

**Issue by MrHoneyB** [anikfal/PostWRF#39]
When we are only doing the simulation for particulate matter (PM10 and PM2.5), what to specify in spc_map?
When I am running ./set_mozbc_input.sh, it is executed successfully but the spc_map is blank.
I am using chem_opt=10

**Comment by anikfal** [comment]
It is actually not blank, since the variables associated to `spc_map` are listed below it:
```
spc_map =
'o3 -> O3',
'no -> NO',
'no2 -> NO2',
'no3 -> NO3',
...
...
```

**Comment by anikfal** [comment]
I think you need spin up time anyway, since it's more related to the meteorological processes, rather than atmospheric chemistry.
