### ISSUE TITLE
inner domain distortion postwrf

### ISSUE THREAD

**Issue by fipoucat** [anikfal/postwrf#42]
@anikfal: I found something strange when looking at my inner domain when I used PostWRF compared to direct ncl use and shapefile overlay. I can't figure out what is causing the problem in PostWRF.
![out_d03_direct_ncl](https://github.com/anikfal/PostWRF/assets/3116845/f90df64a-6b2e-4acf-a9dd-3bfe608a2998)
![outputd03-PostWRF](https://github.com/anikfal/PostWRF/assets/3116845/3d47bd03-d61c-4a09-a3db-7d82998905fe)

**Comment by anikfal** [comment]
Do you mean the wind barbs are missing on the PostWRF's plot?

**Comment by fipoucat** [comment]
Thank you Anikfal again for this important package you developed.

In fact, I am not talking about the parameters but the domain contour distortion mainly in the westernmost side You can look at this part more visible when you compare it 
[wrfout_D03.nc.gz](https://github.com/anikfal/PostWRF/files/14469505/wrfout_D03.nc.gz)
with the shapefile overlay on the PostWRF figure. I try to attach one time slot in the wrfout file for you to better investigate

**Comment by fipoucat** [comment]
![outputd031-PostWRF](https://github.com/anikfal/PostWRF/assets/3116845/e2039e07-5724-4646-a5ac-6c4795e1ff21)

**Comment by anikfal** [comment]
Contour plots by NCL have 3 resolution: low, medium, and high. In PostWRF, the medium resolution has been applied. The high resolution borders need extra data which are not inside NCL. But they can be provided.
So because your shapefile is high resolution, this distortion happened, when you overlay them.

Anyway, I'll consider this issue as an enhancement for the next PostWRF version.

**Comment by fipoucat** [comment]
Hello @anikfal I was wondering when do you plan to add this enhancement which will be very helpful in my current postprocessing.

Thank you

**Comment by anikfal** [comment]
Hi,
Yes. It is now added. In `namelist.wrf` you will find two new variables in `WRF Contour Plot` section: `HighRes_coastline_on_off` and `HighRes_coastline_data_path`.

If you want to apply the high resolution coastlines on your plots, you need to set `HighRes_coastline_on_off` to 1. But before that, you must download the high resolution data from the link below:
https://www.io-warnemuende.de/files/staff/rfeistel/download/mapper.zip

 Then put the downloaded data into a directory and unzip it. Then you need to set `HighRes_coastline_data_path` to that directory and run `./postwrf.sh`

**Comment by fipoucat** [comment]
OK, the domain is correct now., that's great

A pending problem now (maybe memory) can only plot one direct parameter. If it is a computed one it stays for hours without plotting.
Enter the number of the favored file: 3

wrfout_d03_2022-06-02_130000 has been selected

rev: stdin: 0: Invalid or incomplete multibyte or wide character
Plotting  contour maps ...

 
Specify Time_Step(s) Between The Images (Default=1):
Time_Step Has Been Set To 1

 Specify The Method Of Drawing Contours (1 or 2) for rh/100:
1) Automatic
2) Manual
#? 1

Contour Lines Will Be Set Automatically ...

Select a color pattern from the list below (a number from 1 to 10) for rh/100::
1) Rainbow-start_from_blue 6) Red
2) Rainbow-start_from_red 7) Green
3) Rainbow-start_from_white 8) White..Yellow..Orange..Red
4) Blue..Red 9) White..Black
5) Blue 10) Black..White
#? 5

 Format Of The Images: 1, 2, 3, or 4?
1) x11
2) pdf
3) png
4) animated_gif
#? 1
Please wait. NCL is processing ...

Please wait. NCL is processing ...

Contour 3: Name of the polynomial rh/100 ?

**Comment by anikfal** [comment]
In the last line, what happens if you put a name for `rh/100` and press Enter? It seems there is no problem. It is waiting for your response.

**Comment by fipoucat** [comment]
sorry that was the problem, did not pay attention to that.
Wonderful,
Many thanks
