### ISSUE TITLE
Impossibility to install POSTWRF

### ISSUE THREAD

**Issue by Nikolaidis8416** [anikfal/postwrf#44]
Good morning, I have the next problem installing POSTWRF:

The authenticity of host 'github.com (140.82.114.4)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Please, I require support for solve it.

Best regards.

**Comment by anikfal** [comment]
Hi,
Please try cloning the HTTPS link of the software, instead of the SSH link.
