### ISSUE TITLE
Problem with Shaded Conour plot

### ISSUE THREAD

**Issue by Krish1015** [anikfal/postwrf#45]
Hello All, 
PostWRF is a great tool for the Analysis of WRF output, but somehow, the shaded contour plot is not working for me, while the other is working very fine; it's all white all over the area, but the colour bar is showing a range. Can you please help with this? It's very urgent!

I am attaching the namelist file and the output to this email. Please help me.

![spatialplot-wrfout_d01 000003](https://github.com/anikfal/postwrf/assets/112240901/1e8abd70-0402-4efc-ae6a-640249fba808)
[namelist.odt](https://github.com/anikfal/postwrf/files/15421955/namelist.odt)

The link for wrf file : https://iitbacin-my.sharepoint.com/:u:/g/personal/22m1436_iitb_ac_in/Eejx_LFHeeVNsViXVyAWlsQB6TW11cts52rZutdgcHxcOw?e=0W0foJ

**Comment by anikfal** [comment]
Hi. Please apply the command below on your `wrfout_file` and send `out.nc` to me:
`ncks -d Time,1,2 wrfout_file out.nc`

**Comment by Krish1015** [comment]
Here is the output of the code as out.nc

Link : https://iitbacin-my.sharepoint.com/:u:/g/personal/22m1436_iitb_ac_in/ETf6q9RIhdxNv8jHt-azDf8B77ZUZLB-pKdBg23w-SHxig?e=XKMfxo

**Comment by Krish1015** [comment]
Hello All,
Is there any update for the issue? I am still waiting for your response.

**Comment by anikfal** [comment]
Hi. The `out.nc` file you sent to me could be potted by PostWRF, with your `namelist.wrf`:

![contour-level-wrfout_d04 000001](https://github.com/anikfal/postwrf/assets/11738727/69bd80d1-88be-47ae-874f-d22179b74c60)
So there might be some problem with your installation. You can run it again and send me all the messages you get during the run process.
