### ISSUE TITLE
Can postwrf be used on ubuntu?

### ISSUE THREAD

**Issue by qwdy** [anikfal/postwrf#46]
I'm using Ubuntu18.04 and install ncl 6.4.0 by command `sudo apt install ncl-ncarg`. I also `echo 'export NCARG_ROOT=/usr' >> ~/.bashrc` `source ~/.bashrc`

Now I met an error when running postwrf:
`fatal:Could not open ($NCARG_ROOT/lib/ncarg/nclscripts/csm/gsn_code.ncl)
fatal:error at line 1 in file /home/coawst/Build_COAWST/COAWST/Tools/postwrf-master/modules/contourlvl.ncl
fatal:syntax error: line -1 before or near  
^
fatal:error in statement`.

What should I do?

**Comment by qwdy** [comment]
I found at line 1 in file /home/coawst/Build_COAWST/COAWST/Tools/postwrf-master/modules/contourlvl.ncl, there are 5 command strated with "load". However I don't have 'load' in my ubuntu. 
`Command 'load' not found, did you mean:
  command 'nload' from deb nload
  command 'tload' from deb procps
  command 'xload' from deb x11-apps
  command 'olad' from deb ola
Try: apt install <deb name>`
Is this the reason causing the error?

**Comment by anikfal** [comment]
Hi. If `ncl` is installed on your system, it is probably installed to `/usr/share/ncarg`. So please run the command below and try PostWRF again:
`sudo ln -s /usr/share/ncarg /usr/lib/ncarg`

**Comment by qwdy** [comment]
Hi I tried but it didn't work. I reinstall the ncl and chmod +x again, but still the same error

**Comment by qwdy** [comment]
I fixed it. I think  my ncl v6.4.0 downloaded by `sudo apt install ncl-ncarg` has some problems which I don't figure out. I installed the ncl v6.6.2 following [https://www.ncl.ucar.edu/Download/index.shtml](url). 

ps: Why can't I close the X11 image window unless I click on the last valid time?

**Comment by anikfal** [comment]
Okay. Good that you handled it.
Press `Ctrl+C` to close an X11 window.
