### ISSUE TITLE
dust plot under PBL

### ISSUE THREAD

**Issue by fipoucat** [anikfal/postwrf#47]
Hello,

I want to plot dust from wrfchem simulation but want DUST1+DUST2+DUST3+DUST4+DUST5 integrated between the surface and 850 hPa. Can it be done by PostWRF? With which command?

Thank you

**Comment by anikfal** [comment]
Hi
You can get it by using dust_total as the variable. It can only be extracted on the surface level by PostWRF. But you can also plot its cross section or vertical plot from surface to the top of atmosphere.
