### ISSUE TITLE
some questions on plotting

### ISSUE THREAD

**Issue by qwdy** [anikfal/postwrf#48]
Hi, I have 2 questions about plotting:

1) When I use shaded contour function for some variables (like U10,V10,isoprene...), the image I got only display the color within land area which means it lost the ocean part. If I use ncview to look U10,then whole domain can display U10. I attach a U10 image for better understanding. I also turn on wind sector function and it displays the wind of land+ocean which satisfy my need. So how can I get an image with the color of the variable display in land+ocean?
![image](https://github.com/anikfal/postwrf/assets/146046421/2e5ed29a-cc3e-4540-a529-c0f883f35708)

2)When I use panel plot function, I get some imcompleteness and I find clorbar is too far away from the images. How to modify legend like "delete init:2022:07:02_12:00:00" or "adjust the distance between colorbar and image"
![image](https://github.com/anikfal/postwrf/assets/146046421/aa2fe139-b632-4cda-a0d4-1d5c4d66c8c1)

3) I want to confirm that the wind sector function caculate wind speed by (u2+v2)*0.5 internally?

**Comment by anikfal** [comment]
Hi. Please pay attention to the options you have in the `GENERAL SETTINGS` section of `namelist.wrf`.
By setting `map_filled_ocean_on_off = 0`, you will get the desired plots you discussed about.
