### ISSUE TITLE
How to Write IVT equation in PostWRF

### ISSUE THREAD

**Issue by LJroy1998** [anikfal/postwrf#49]
@anikfal I was trying by using this approach For first two levels, i have taken the average q, u, v, and compute q*u and q*v for it.
similarly, for the second and third level, and so on to the last level. All all the qu values over all the levels to get integrated vapor flux in u direction, call it QU. (I have also multiply the entire terms by 1/g to make is flux in kgm-1-1). Similalrly, i find the integrated flux in v direction QV. After this, i have taken the square root of the QU and QV vector to give you IVT. But still it not there if you have derived some equation already please help me in that.

**Comment by anikfal** [comment]
Sorry I am not sure what you are talking about. Does IVT stand for the Intermediate Value Theorem? Please clarify in more details, providing `namelist.wrf` if you are using PostWRF.

**Comment by LJroy1998** [comment]
I am talking about Intrgrated vapour transport equation how to write that into PostWRF. I am attaching the IVT equation and the namelist.wrf file.
[namelist.wrf.docx](https://github.com/user-attachments/files/16050689/namelist.wrf.docx)
![IVT](https://github.com/anikfal/postwrf/assets/152192621/8125b661-b5da-45f5-8bd2-eef9a1922de6)

**Comment by anikfal** [comment]
Integrals are not supported by PostWRF. Only polynomials with the main mathematical operations (addition, multiplication, etc.) can be put into namelist.wrf.

**Comment by LJroy1998** [comment]
okay, thank you for your help.
