### ISSUE TITLE
Blank map , and postwrf_wrfout*': No such file or directory

### ISSUE THREAD

**Issue by raedh80** [anikfal/postwrf#54]
i keep getting this issue , also even if map generate for example T2 map is generated without coloring just white map 

this is my directory
azureuser@WRFAmm:~/PostWRF$ ls
LICENCE.txt  modules_era   wrfout_d01_2024-11-23_12:00:00  wrfout_d01_2024-11-23_14:00:00
README.md    namelist.wrf  wrfout_d01_2024-11-23_12:30:00  wrfout_d01_2024-11-23_14:30:00
docs         outputs_      wrfout_d01_2024-11-23_13:00:00
modules      postwrf.sh    wrfout_d01_2024-11-23_13:30:00
azureuser@WRFAmman2km:~/PostWRF$ 

azureuser@WRFAmm:~/PostWRF$ ./postwrf.sh -debug
------------------------------------------------------------
        List of choosable diagnostic variables
------------------------------------------------------------
1)  avo           ( Absolute Vorticity [10-5 s-1])
2)  eth           ( Equivalent Potential Temperature [K] )
3)  cape_surface  ( 2D fields of CAPE [J/kg] )
4)  cin_surface   ( 2D fields of CAPE [J/kg] )
5)  cape_3d       ( 3D fields of CAPE [J/kg] )
6)  cin_3d        ( 3D fields of CAPE [J/kg] )
7)  ctt           ( Cloud Top Temperature [degC] )
8)  dbz           ( Reflectivity [dBZ] )
9)  mdbz          ( Maximum reflectivity [dBZ] )
10) geopt         ( Full model geopotential [m2 s-2] )
11) geopotential  ( Full model geopotential [m2 s-2] )
12) helicity      ( Storm Relative Helicity [m-2/s-2] )
13) omg           ( Omega [C] )
14) tk            ( Temperature [K] )
15) p/pres        ( Full model pressure [Pa] )
16) pressure      ( Full model pressure [hPa] )
17) pvo           ( Potential Vorticity [PVU] )
18) pw            ( Precipitable Water - 2D )
19) rh2           ( 2m Relative Humidity [%] )
20) rh            ( Relative Humidity [%] )
21) slp           ( Sea Level Pressure [hpa] )
22) ter           ( Model terrain height [m] )
23) td2           ( 2m dew point temperature [C] )
24) td            ( Dew point temperature [C] )
25) tc            ( Temperature [C] )
26) th/theta      ( Potential temperature [K] )
27) tv            ( Virtual temperature [K] )
28) twb           ( Wet bulb temperature [K] )
29) updraft_helicity ( Updraft helicity [m-2/s-2] )
30) ua            ( U component of wind on mass points )
31) va            ( V component of wind on mass points )
32) wa            ( W component of wind on mass points )
33) z/height      ( Full Model Height [m] )
34) lfc           ( Level of Free Convection )
35) lcl           ( Lifted Condensation Level )
36) dust_total    ( Total Dust Concentration [Microgram/Kg_dry_air] )
37) dust_pm10     ( Dust Concentration equal to PM10 [Microgram/Kg_dry_air] )
38) dust_pm2.5    ( Dust Concentration equal to PM2.5 [Microgram/Kg_dry_air] )
39) wind_s        ( Wind Speed [m/s] - 2D )
40) wind_d        ( Wind Direction [degrees from north] - 2D )
./postwrf.sh: illegal option -- e
./postwrf.sh: illegal option -- b
./postwrf.sh: illegal option -- u
./postwrf.sh: illegal option -- g

========================  PostWRF  ============================
              Run './postwrf.sh -h' to get help                
     Reference any problems on GitHub <github.com/anikfal>     
===============================================================

---------------------------------------------------------
       CONTOUR PLOT                CONTOUR PLOT
---------------------------------------------------------

Plotting  contour maps ...

ls: cannot access '/home/azureuser/PostWRF/postwrf_wrfout*': No such file or directory
basename: missing operand
Try 'basename --help' for more information.
 
Specify Time_Step(s) Between The Images (Default=1): 1

 Specify The Method Of Drawing Contours (1 or 2) for rh/100:
1) Automatic
2) Manual
#? 1

Contour Lines Will Be Set Automatically ...

Select a color pattern from the list below (a number from 1 to 10) for rh/100::
1) Rainbow-start_from_blue       5) Blue                         9) White..Black
2) Rainbow-start_from_red        6) Red                         10) Black..White
3) Rainbow-start_from_white      7) Green
4) Blue..Red                     8) White..Yellow..Orange..Red
#? 1

 Format Of The Images: 1, 2, 3, or 4?
1) x11
2) pdf
3) png
4) animated_gif
#? 3

 Name of the Output File? (Press Enter for the default name): 1111
warning:_NclOpenFile: cannot open file </home/azureuser/PostWRF/outputs_/postwrf_wrfout*>; No such file or directory

fatal:Subscript out of range, error in subscript #0
fatal:An error occurred reading fileatts
fatal:["Execute.c":8637]:Execute: Error occurred at or near line 15 in file read_wrfouts.ncl

**Comment by anikfal** [comment]
Why did you run the tool with a `-debug` flag? Just simply run it without any argument (`./postwrf.sh`). That must be okay.

**Comment by raedh80** [comment]
> Why did you run the tool with a `-debug` flag? Just simply run it without any argument (`./postwrf.sh`). That must be okay.

THanks for quick response, i did this because the generated map with variable 3 for T2  as in attachments so tried to know if there any issue.   Thanks


![GGG-wrfout_d01](https://github.com/user-attachments/assets/6d3b199c-6346-48a3-a81b-cc2405386e43)
![temperature_plot](https://github.com/user-attachments/assets/0e0b8bda-ee6f-4610-9c7d-c56cb3237189)

**Comment by raedh80** [comment]
i read comment in previous closed issues installed NCL 6.4.0 and shading worked.
