### ISSUE TITLE
Something wrong when I run postwrf.sh to convert netCDF to Geotiff on Ubuntu OS

### ISSUE THREAD

**Issue by cybersp** [anikfal/postwrf#56]
I have installed NCL by conda using this code:

conda create -n ncl_env -c conda-forge ncl

And I can get the version of NCL I installed:
![image](https://github.com/user-attachments/assets/d8702b45-869c-41e4-89e5-0bb32a27c1ae)
Here is the full report:
1)
![image](https://github.com/user-attachments/assets/f0962f21-79f2-4a8c-b27e-f291f140a817)
2)
![image](https://github.com/user-attachments/assets/51d1b67d-8aac-4637-96bf-a510dc5e0350)

**Comment by anikfal** [comment]
Is the command `convert` available on your system? If not, you need to install ImageMagick by the command bleow:
```
sudo apt install imagemagick
```

**Comment by cybersp** [comment]
Hi Amir,

I have installed the `convert `command using `sudo apt install imagemagick`, and the version is `ImageMagick 6.9.12-98 Q16 x86_64 18038`. However, I am still encountering the same error. My NCL version is 6.6.2

It seems the file `geo_eq_ok.txt` is missing in the `postwrf-master/modules` directory. 

Thank you for your assistance!

Best regards

**Comment by anikfal** [comment]
Why does your WRF file have a `.nc` suffix? Is it not the original file? Please send me `wrfout_d01_2024-11-19.nc`, so I can better investigate the issue.

**Comment by cybersp** [comment]
Yes, the file I am using has a `.nc` suffix. Since I am unable to upload `.nc` files directly, I have compressed it into a `.zip` file for your reference. 
Thank you for your assistance!
[wrfout_d01_2024-11-19.zip](https://github.com/user-attachments/files/18009495/wrfout_d01_2024-11-19.zip)

**Comment by anikfal** [comment]
Okay. Thanks for sending the file.
I think `wrfout_d01_2024-11-19.nc` is not a standard WRF output. It has been manipulated in some way and does not have any attributes. A standard WRF output must have attributes similar to the list below:
```
$ ncl_filedump wrfout_d01_2023-12-17_12\:00\:00.nc | head -n 55
 Copyright (C) 1995-2019 - All Rights Reserved
 University Corporation for Atmospheric Research
 NCAR Command Language Version 6.6.2
 The use of this software is governed by a License Agreement.
 See http://www.ncl.ucar.edu/ for more details.

Variable: f
Type: file
filename:	wrfout_d01_2023-12-17_12:00:00
path:	wrfout_d01_2023-12-17_12:00:00
Number of Attributes:131
    TITLE	: 	 OUTPUT FROM WRF V4.3 MODEL
    START_DATE	: 	2023-12-17_12:00:00
    SIMULATION_START_DATE	: 	2023-12-17_12:00:00
    WEST-EAST_GRID_DIMENSION	: 	90
    SOUTH-NORTH_GRID_DIMENSION	: 	90
    BOTTOM-TOP_GRID_DIMENSION	: 	45
    DX	: 	30000
    DY	: 	30000
    AERCU_OPT	: 	0
    AERCU_FCT	: 	 1
    IDEAL_CASE	: 	0
    DIFF_6TH_SLOPEOPT	: 	0
    AUTO_LEVELS_OPT	: 	2
    DIFF_6TH_THRESH	: 	0.1
    DZBOT	: 	50
    DZSTRETCH_S	: 	1.1
...
```
But the attributes information in your file are missing:
```
$ ncl_filedump wrfout_d01_2024-11-19.nc | head -n 55
 Copyright (C) 1995-2019 - All Rights Reserved
 University Corporation for Atmospheric Research
 NCAR Command Language Version 6.6.2
 The use of this software is governed by a License Agreement.
 See http://www.ncl.ucar.edu/ for more details.

Variable: f
Type: file
filename:	wrfout_d01_2024-11-19
path:	wrfout_d01_2024-11-19
   file global attributes:
   dimensions:
      iy = 540
      jx = 690
      Time = 1
      south_north = 540
      west_east = 690
      ncl5 = 9
   variables:
      float pre ( iy, jx )
         grid_mapping :	crs
         units :	mm
         long_name :	Precipitation
         _FillValue :	-9999

      integer iy ( iy )
         long_name :	y-coordinate in Cartesian system
         standard_name :	projection_y_coordinate
         units :	m
         axis :	Y
         _CoordinateAxisType :	GeoY

      integer jx ( jx )
         long_name :	x-coordinate in Cartesian system
         standard_name :	projection_x_coordinate
         units :	m
         axis :	X
         _CoordinateAxisType :	GeoX
```
So for the moment, I recommend using the original WRF output.

**Comment by cybersp** [comment]
Thank you for your feedback and for reviewing the file. I understand now that the `wrfout_d01_2024-11-19.nc` file is not a standard WRF output, leading to the absence of necessary attributes.

I will check the source of this file and try to obtain the original, unaltered WRF output that includes the required attributes. Once I have the correct file, I’ll test again and reach out if further assistance is needed.

Thank you for your guidance!
