### ISSUE TITLE
error running postzrf.sh

### ISSUE THREAD

**Issue by fipoucat** [anikfal/postwrf#57]
I a; getting the following error and wonder what is causing this

? 1
Please wait. NCL is processing ...

warning:toint: A bad value was passed (string); input strings must contain numeric digits, replacing with missing value
fatal:The result of the conditional expression yields a missing value. NCL can not determine branch, see ismissing function
fatal:["Execute.c":8637]:Execute: Error occurred at or near line 1008 in file /home/parallels/work/postwrf-master/modules/contourlvl.ncl

**Comment by anikfal** [comment]
Can you provide the complete information printed on the screen, including `namelist.wrf`?

**Comment by fipoucat** [comment]
(ncl_stable) parallels@debian:~/work/postwrf-master$ ./postwrf.sh 

========================  PostWRF  ============================
              Run './postwrf.sh -h' to get help                
     Reference any problems on GitHub <github.com/anikfal>     
===============================================================

---------------------------------------------------------
       CONTOUR PLOT                CONTOUR PLOT
---------------------------------------------------------

There are multiple wrf-files in the current directory:

   1) wrfout_d01_2002-01-06_00
   2) wrfout_d01_2002-01-06_000000
   3) wrfout_d01_2002-01-07_000000
   4) wrfout_d01_2002-01-08_000000
   5) wrfout_d01_2002-01-09_000000
   6) wrfout_d01_2002-01-10_000000
   7) wrfout_d01_2002-01-11_000000
   8) wrfout_d01_2002-01-12_000000
   9) wrfout_d01_2002-01-13_000000
   10) wrfout_d01_2002-01-14_000000
   11) wrfout_d01_2002-01-15_000000

Enter the number of the favored file: 1

wrfout_d01_2002-01-06_00 has been selected

Plotting  contour maps ...

 
Specify Time_Step(s) Between The Images (Default=1): 
Time_Step Has Been Set To 1

 Format Of The Images: 1, 2, 3, or 4?
1) x11
2) pdf
3) png
4) animated_gif
#? 1
Please wait. NCL is processing ...

warning:toint: A bad value was passed (string); input strings must contain numeric digits, replacing with missing value
fatal:The result of the conditional expression yields a missing value. NCL can not determine branch, see ismissing function
fatal:["Execute.c":8637]:Execute: Error occurred at or near line 1008 in file /home/parallels/work/postwrf-master/modules/contourlvl.ncl
[namelist.wrf.gz](https://github.com/user-attachments/files/18114871/namelist.wrf.gz)

**Comment by anikfal** [comment]
I think there is some issue with your `namelist.wrf`. You are also using an old version of the tools. To work around it, please pull PostWRF, or `git clone` it again and use the new version.
