### ISSUE TITLE
Error plotting Reflectivity (dbz variable)

### ISSUE THREAD

**Issue by ADgit7** [anikfal/postwrf#58]
Hi, 

I have been able to plot variables such as surface pressure (slp) in shaded contours but I would like to plot reflectivity with shaded contours however I am having an issue. Editing namelist.wrf and using '3rd_Variable_name              = dbz', results in the following output:

"Please wait. NCL is processing ...

Error: one or more contour variables in namelist.wrf are not valid for postwrf_wrfout_d01_2021-07-03_00"

Is there another setting in namelist.wrf that needs to be changed or is this due to the wrfout file?

Attached is a a text file of my namelist.wrf file.

[namelist_wrf.txt](https://github.com/user-attachments/files/18275339/namelist_wrf.txt)

**Comment by anikfal** [comment]
Hi,

I think you can work around this issue by removing the tab after `'3rd_Variable_name = dbz   ` and have it as `3rd_Variable_name = dbz`.

You can also pull the tool, or `git clone git@github.com:anikfal/postwrf.git` again. The redundant tabs can be handled automatically in the new version.

**Comment by ADgit7** [comment]
> Hi,
> 
> I think you can work around this issue by removing the tab after `'3rd_Variable_name = dbz ` and have it as `3rd_Variable_name = dbz`.
> 
> You can also pull the tool, or `git clone git@github.com:anikfal/postwrf.git` again. The redundant tabs can be handled automatically in the new version.

Noted, removing the tab/extra space at the end indeed resolved the issue. 
Thank you for your assistance!
