### ISSUE TITLE
Not working with custom named wrfout files

### ISSUE THREAD

**Issue by sudhansu-s-rath** [anikfal/PostWRF#7]
The wrfout files need to be copied or linked with original name.
Is there a way to make it work for renamed wrfout files??
Default name of wrfout files: wrfout_d03_2015-07-25_00:00:00
My wrfout file name: wrfout_25Jul2019_d03_2015-07-25_00:00:00:

**Comment by anikfal** [comment]
@sudhansu-s-rath
PostWRF needs a prefix for the WRF file names to distinguish them from other files. This prefix is **wrfout_d**.
In other words, you can change the names of the WRF outputs, but you must keep the prefix unchanged.

For the file wrfout_d03_2015-07-25_00:00:00, in addition to the original file name, the sample names below are also acceptable and recognizable by PostWRF as a WRF output file name:
- wrfout_d03_myname
- wrfout_d03myname
- wrfout_d03_run1
- wrfout_d03run2
