### ISSUE TITLE
ncl: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Anielal** [anikfal/PostWRF#9]
Hi all,
I am trying to get a domain plot from wrf out file using postWRF. I have **3 domains**. But I am getting the error:

'**ncl: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory'**.

I tried 'sudo apt-get install gsl-bin' to install gsl in my **ubuntu 20.04**, but still it is showing this same error. 

Kindly help me solve this issue.

Looking forward to any kind of help
Thank you

**Comment by anikfal** [comment]
Hi,

The error you mentioned about libgsl.so.25 is a NCL installation issue.
Also please note that PostWRF is developed in CentOS/Fedora OS, and there might be some issues while running it in Ubuntu.

What do you get if you run the command bellow?
`find /usr/lib64/ | grep libgsl`

**Comment by Anielal** [comment]
![Screenshot from 2022-08-05 15-47-52](https://user-images.githubusercontent.com/93431607/183057463-5d1d76ef-875c-4abb-b8d4-5ab3d7dc0470.png)
kindly find the screenshot attached

**Comment by anikfal** [comment]
It seems no libgsl is installed on you machine.

How did you install NCL?

**Comment by Anielal** [comment]
i installed ncl with 'conda'
conda create -n ncl_stable -c conda-forge ncl

**Comment by anikfal** [comment]
Install it by apt-get, as bellow:
`sudo apt-get -y install ncl-ncarg`

Do not use any conda environment for PostWRF.

**Comment by Anielal** [comment]
yes

**Comment by Anielal** [comment]
I installed ncl as suggested. Now its showing some other error. 
pfa screenshot.
![Screenshot from 2022-08-05 16-49-42](https://user-images.githubusercontent.com/93431607/183067619-384ae978-5858-4d94-8826-c432a9aa471b.png)

**Comment by Anielal** [comment]
Also, it is asking for only 2 domains, whereas I have 3 domains.!

**Comment by anikfal** [comment]
In the namelist.wrf section, the value of `+number_of_domains (topography)` must be equal to the number of domains (for your case is 3):
```
Domain_On-Off                    = 0

namelist.wps_path (schematic)   = /home/anikfal/WRF4.2.2/WPS/namelist.wps
background_color (schematic)    = forestgreen
lables_On-Off (schematic)       = 0

+Domain_on_off (topography)      = 1
 +number_of_domains (topography) = 3
 +box_color                      = white
```
Also you can use your namelist.wps to plot the domains by setting ```+Domain_on_off (topography)``` to 0

```
Domain_On-Off                    = 1

namelist.wps_path (schematic)   = /home/anikfal/WRF4.2.2/WPS/namelist.wps
background_color (schematic)    = forestgreen
lables_On-Off (schematic)       = 0

+Domain_on_off (topography)      = 0
 +number_of_domains (topography) = 3
 +box_color                      = white
```

You must set ```namelist.wps_path (schematic)``` to the path of your namelist.wps.

**Please note that PostWRF is best to be run on CentOS or Fedora.**

**Comment by Anielal** [comment]
okay. Thanks for the help
